longoria_era = [
    "Alexis Sánchez",
    "Álvaro González",
    "Amine Harit",
    "Arkadiusz Milik",
    "Bamba Dieng",
    "Boubacar Kamara",
    "Bouna Sarr",
    "Cédric Bakambu",
    "Cengiz Ünder",
    "Chancel Mbemba",
    "Cheick Souaré",
    "Christopher Rocchia",
    "Darío Benedetto",
    "Dimitri Payet",
    "Duje Ćaleta-Car",
    "Eric Bailly",
    "Florian Thauvin",
    "Gerson",
    "Hiroki Sakai",
    "Isaak Touré",
    "Issa Kaboré",
    "Jonathan Clauss",
    "Jordan Amavi",
    "Jordan Veretout",
    "Kevin Strootman",
    "Konrad de la Fuente",
    "Leonardo Balerdi",
    "Luan Peres",
    "Lucas Perrin",
    "Luis Henrique",
    "Luis Suárez",
    "Marley Aké",
    "Mattéo Guendouzi",
    "Maxime López",
    "Michaël Cuisance",
    "Morgan Sanson",
    "Nemanja Radonjić",
    "Nuno Tavares",
    "Olivier Ntcham",
    "Oussama Targhalline",
    "Pape Gueye",
    "Pau López",
    "Pol Lirola",
    "Rubén Blanco",
    "Saîf-Eddine Khaoui",
    "Salim Ben Seghir",
    "Samuel Gigot",
    "Sead Kolašinac",
    "Steve Mandanda",
    "Valentin Rongier",
    "Valère Germain",
    "William Saliba",
    "Yohann Pelé",
    "Yuto Nagatomo",
]

eyraud_era = [
    "Aaron Leya Iseka",
    "Abou Diaby",
    "Adil Rami",
    "Álvaro González",
    "Antoine Rabillard",
    "Arkadiusz Milik",
    "Aymen Abdennour",
    "Bafétimbi Gomis",
    "Bamba Dieng",
    "Boubacar Kamara",
    "Bouna Sarr",
    "Cheick Souaré",
    "Christopher Rocchia",
    "Clinton N'Jie",
    "Darío Benedetto",
    "Dimitri Payet",
    "Dória",
    "Duje Ćaleta-Car",
    "Florian Chabrolle",
    "Florian Thauvin",
    "André-Frank Zambo Anguissa",
    "Grégory Sertic",
    "Henri Bedimo",
    "Hiroki Sakai",
    "Isaac Lihadji",
    "Jordan Amavi",
    "Karim Rekik",
    "Kevin Strootman",
    "Konstantinos Mitroglou",
    "Lassana Diarra",
    "Leonardo Balerdi",
    "Lucas Ocampos",
    "Lucas Perrin",
    "Luis Henrique",
    "Luiz Gustavo",
    "Mario Balotelli",
    "Marley Aké",
    "Maxime López",
    "Michaël Cuisance",
    "Morgan Sanson",
    "Nemanja Radonjić",
    "Olivier Ntcham",
    "Pape Gueye",
    "Patrice Evra",
    "Pol Lirola",
    "Rémy Cabella",
    "Rod Fanni",
    "Rolando",
    "Romain Alessandrini",
    "Saîf-Eddine Khaoui",
    "Steve Mandanda",
    "Tomáš Hubočan",
    "Valentin Rongier",
    "Valère Germain",
    "William Vainqueur",
    "Yohann Pelé",
    "Yusuf Sari",
    "Yuto Nagatomo",
    "Zinédine Machach",
]

labrune_era = [
    "Abdelaziz Barrada",
    "Abou Diaby",
    "Alaixys Romao",
    "Alou Diarra",
    "André Ayew",
    "André-Pierre Gignac",
    "Antoine Rabillard",
    "Baptiste Aloé",
    "Benjamin Mendy",
    "Benoît Cheyrou",
    "Bilal Boutobba",
    "Bill Tuiloma",
    "Billel Omrani",
    "Bouna Sarr",
    "Brandão",
    "Brice Dja Djédjé",
    "Brice Samba",
    "César Azpilicueta",
    "Charles Kaboré",
    "Chris Gadi",
    "Dimitri Payet",
    "Djimi Traoré",
    "Fabrice Apruzesse",
    "Florian Raspentino",
    "Florian Thauvin",
    "Foued Kadir",
    "André-Frank Zambo Anguissa",
    "Gaël Andonian",
    "Georges-Kévin Nkoudou",
    "Giannelli Imbula",
    "Javier Manquillo",
    "Jean-Philippe Sabo",
    "Jérémie Porsan-Clémenté",
    "Jérémy Morel",
    "Joey Barton",
    "Jordan Ayew",
    "Karim Rekik",
    "Kassim Abdallah",
    "Lassana Diarra",
    "Laurent Abergel",
    "Loïc Rémy",
    "Lucas Mendes",
    "Lucas Ocampos",
    "Lucas Silva",
    "Lucho González",
    "Mario Lemina",
    "Mathieu Valbuena",
    "Mauricio Isla",
    "Michy Batshuayi",
    "Modou Sougou",
    "Momar Bangoura",
    "Morgan Amalfitano",
    "Nicolas Nkoulou",
    "Paolo De Ceglie",
    "Rafidine Abdullah",
    "Rémy Cabella",
    "Rod Fanni",
    "Rolando",
    "Romain Alessandrini",
    "Saber Khalifa",
    "Souleymane Diawara",
    "Stéphane Mbia",
    "Stéphane Sparagna",
    "Steve Mandanda",
    "Steven Fletcher",
    "Wesley Jobello",
    "Yohann Pelé",
]

diouf_dassier_era = [
    "Abdoulaye Méïté",
    "Alain Cantareil",
    "Elinton Andrade",
    "André Ayew",
    "André Luis",
    "André-Pierre Gignac",
    "Andrés Mendoza",
    "Bakari Koné",
    "Benoît Cheyrou",
    "Boštjan Cesar",
    "Boudewijn Zenden",
    "Brandão",
    "Cédric Carrasso",
    "César Azpilicueta",
    "Charles Kaboré",
    "Christian Giménez",
    "Cyril Rool",
    "Delfim",
    "Demetrius Ferreira",
    "Djibril Cissé",
    "Édouard Cissé",
    "Elamine Erbate",
    "Elliot Grandin",
    "Fabien Barthez",
    "Fabrice Abriel",
    "Fernando Morientes",
    "Franck Ribéry",
    "Frédéric Déhu",
    "Gabriel Heinze",
    "Gaël Givet",
    "Garry Bocaly",
    "Guy Gnabouyou",
    "Habib Bamogo",
    "Habib Beye",
    "Hatem Ben Arfa",
    "Hilton",
    "Jacques Faty",
    "Jérôme Bonnissel",
    "Jordan Ayew",
    "Juan Krupoviesa",
    "Julien Rodriguez",
    "Kanga Akalé",
    "Karim Ziani",
    "Koji Nakata",
    "Koke",
    "Laurent Batlles",
    "Laurent Bonnart",
    "Leyti N'Diaye",
    "Loïc Rémy",
    "Lorik Cana",
    "Lucho González",
    "Mamadou Niang",
    "Mamadou Samassa",
    "Mame N'Diaye",
    "Mathieu Valbuena",
    "Matt Moussilou",
    "Mickaël Pagis",
    "Modeste M'bami",
    "Mohamed Dennoun",
    "Pape M'Bow",
    "Péguy Luyindula",
    "Rahmane Barry",
    "Renato Civelli",
    "Rod Fanni",
    "Ronald Zubar",
    "Rudy Riou",
    "Sabri Lamouchi",
    "Salim Arrache",
    "Salomon Olembé",
    "Samir Nasri",
    "Souleymane Diawara",
    "Stéphane Mbia",
    "Steve Mandanda",
    "Sylvain Wiltord",
    "Taye Taiwo",
    "Thomas Deruda",
    "Toifilou Maoulida",
    "Tyrone Mears",
    "Vincent Gragnic",
    "Wilson Oruma",
]

bouchet_era = [
    "Abdoulaye Méïté",
    "Ahmed Yahiaoui",
    "Benoît Pedretti",
    "Bixente Lizarazu",
    "Brahim Hemdani",
    "Bruno Cheyrou",
    "Camel Meriem",
    "Cédric Carrasso",
    "Cyril Chapuis",
    "Daniel Van Buyten",
    "David Sommeil",
    "Delfim",
    "Demetrius Ferreira",
    "Didier Drogba",
    "Djamel Belmadi",
    "Dmitri Sychev",
    "Eduardo Costa",
    "Eduardo Tuzzio",
    "Fabien Barthez",
    "Fabien Camus",
    "Fabien Laurenti",
    "Fabio Celestini",
    "Fabrice Fiorèse",
    "Fernandão",
    "Frank Leboeuf",
    "Frédéric Déhu",
    "Habib Bamogo",
    "Habib Beye",
    "Ibrahima Bakayoko",
    "Jérémy Gavanon",
    "Jérôme Pérez",
    "Johnny Ecker",
    "Koji Nakata",
    "Koke",
    "Lamine Sakho",
    "Laurent Batlles",
    "Laurent Merlin",
    "Leyti N'Diaye",
    "Manuel dos Santos",
    "Mathieu Flamini",
    "Michel Gafour",
    "Mickaël Marsiglia",
    "Mido",
    "Pascal Johansen",
    "Péguy Luyindula",
    "Philippe Christanval",
    "Piotr Świerczewski",
    "Rahmane Barry",
    "Rudi Skácel",
    "Salomon Olembé",
    "Samir Nasri",
    "Sébastien Pérez",
    "Štěpán Vachoušek",
    "Steve Marlet",
    "Sylvain N'Diaye",
    "Taye Taiwo",
    "Therry Racon",
    "Vedran Runje",
]

rld_era = [
    "Abdoulaye Méïté",
    "Alberto Malusci",
    "Alberto Rivera",
    "Alen Škoro",
    "Alfonso Pérez",
    "André Luiz",
    "Andreas Köpke",
    "Arthur Moses",
    "Benjamin Gavanon",
    "Brahim Hemdani",
    "Bruno N'Gotty",
    "Cédric Mouret",
    "Chris Makin",
    "Christophe Dugarry",
    "Christophe Galtier",
    "Claude Makélélé",
    "Cyril Chapuis",
    "Cyril Domoraud",
    "Cyril Rool",
    "Cyrille Pouget",
    "Damien Gregorini",
    "Daniel Bravo",
    "Daniel Montenegro",
    "Daniel Van Buyten",
    "Delfim",
    "Dill",
    "Dimas",
    "Djamel Belmadi",
    "Dramane Coulibaly",
    "Edson",
    "Eduardo Berizzo",
    "Eduardo Tuzzio",
    "Éric Decroix",
    "Éric Roy",
    "Fabien Laurenti",
    "Fabrice Fernandes",
    "Fabrizio Ravanelli",
    "Fernandão",
    "Florian Maurice",
    "Franck Dumas",
    "Franck Jurietti",
    "François Lemasson",
    "Frank Leboeuf",
    "Frédéric Brando",
    "George Weah",
    "Guillaume Deschamps",
    "Hamada Jambay",
    "Ibrahim Ba",
    "Ibrahima Bakayoko",
    "Iván de la Peña",
    "Ivan Franceschini",
    "Jacques Abardonado",
    "Jean-Philippe Durand",
    "Jean-Pierre Cyprien",
    "Jérôme Alonzo",
    "Jérôme Leroy",
    "Jocelyn Gourvennec",
    "Joseph Yobo",
    "Jovan Stanković",
    "Jürgen Cavens",
    "Kaba Diawara",
    "Karim Dahou",
    "Klas Ingesson",
    "Lamine Sakho",
    "Laurent Blanc",
    "Laurent Spinosi",
    "Lilian Martin",
    "Loris Reina",
    "Lucas Bernardi",
    "Ludovic Asuar",
    "Manuel dos Santos",
    "Marc Libbra",
    "Marcelinho Paraíba",
    "Martial Robin",
    "Mehdi Ben Slimane",
    "Mickaël Marsiglia",
    "Miladin Bečanović",
    "Olivier Echouafni",
    "Pablo Calandria",
    "Pascal Nouma",
    "Patrick Blondeau",
    "Patrick Colleter",
    "Peter Luccin",
    "Philippe Brunel",
    "Pierre Issa",
    "Piotr Świerczewski",
    "Reynald Pedros",
    "Richard Martini",
    "Robert Pires",
    "Salomon Olembé",
    "Sébastien Pérez",
    "Serge Blanc",
    "Seydou Keita",
    "Stefano Torrisi",
    "Stéphane Dalmat",
    "Stéphane Porato",
    "Stéphane Trévisan",
    "Tchiressoua Guel",
    "Teddy Bertin",
    "Titi Camara",
    "Tony Cascarino",
    "Vedran Runje",
    "Victor Agali",
    "Wilfried Dalmat",
    "William Gallas",
    "Xavier Gravelaine",
    "Yannick Fischer",
    "Yordan Letchkov",
    "Zoumana Camara",
]

l2_era = [
    "Andrew Tembo",
    "Bernard Casoni",
    "Bruno Germain",
    "Christophe Galtier",
    "Fabien Barthez",
    "Fabrice Moreau",
    "Frédéric Tatarian",
    "Guillaume Deschamps",
    "Hamada Jambay",
    "Jean-François Hernandez",
    "Jean-Manuel Thetis",
    "Jean-Marc Ferreri",
    "Jean-Philippe Durand",
    "Jérôme Alonzo",
    "Joël Cantona",
    "Laurent Spinosi",
    "Ludovic Asuar",
    "Manuel Amoros",
    "Marc Libbra",
    "Marcel Dib",
    "Michel De Wolf",
    "Nenad Bjeković",
    "Olivier Echouafni",
    "Stéphane Mazzolini",
    "Tony Cascarino",
    ]

tapie_era = [
    "Abdoulaye Diallo",
    "Abedi Pele",
    "Alain Boghossian",
    "Alain Giresse",
    "Alain Roche",
    "Alen Bokšić",
    "Ali Bouafia",
    "Basile Boli",
    "Benoît Cauet",
    "Bernard Casoni",
    "Bernard Genghini",
    "Bernard Pardo",
    "Blaž Slišković",
    "Bruno Germain",
    "Carlos Mozer",
    "Carmelo Micciche",
    "Chris Waddle",
    "Christophe Galtier",
    "Claude Lowitz",
    "Daniel Dutuel",
    "Daniel Xuereb",
    "Didier Deschamps",
    "Didier Santini",
    "Dragan Stojković",
    "Enzo Francescoli",
    "Eric Cantona",
    "Éric Di Meco",
    "Éric Lada",
    "Éric Mura",
    "Fabien Barthez",
    "Fabrice Henry",
    "Franck Passi",
    "Franck Sauzée",
    "François Brisson",
    "François Omam-Biyik",
    "Frédéric Meyrieu",
    "Gaëtan Huard",
    "Hamada Jambay",
    "Henri Stambouli",
    "Igor Dobrovolski",
    "Jacky Bonnevay",
    "Jean Castaneda",
    "Jean Tigana",
    "Jean-Christophe Thomas",
    "Jean-François Domergue",
    "Jean-Jacques Eydelie",
    "Jean-Louis Zanon",
    "Jean-Marc Ferreri",
    "Jean-Philippe Durand",
    "Jean-Pierre Bade",
    "Jean-Pierre Papin",
    "Jocelyn Angloma",
    "José Anigo",
    "Joseph-Antoine Bell",
    "Karlheinz Förster",
    "Klaus Allofs",
    "Laurent Fournier",
    "Manuel Amoros",
    "Marc Libbra",
    "Marcel Desailly",
    "Pascal Baills",
    "Pascal Fugier",
    "Pascal Olmeta",
    "Patrick Cubaynes",
    "Patrick Delamontagne",
    "Paulo Futre",
    "Philippe Vercruysse",
    "Rudi Völler",
    "Rui Barros",
    "Sonny Anderson",
    "Thierry Laurey",
    "Trevor Steven",
    "William Ayache",
    "William Prunier",
    "Yvon Le Roux",
]

all_players = list(set(longoria_era + eyraud_era + labrune_era + diouf_dassier_era + bouchet_era + rld_era + l2_era + tapie_era))